### ISSUE TITLE
I'm getting  the error "markRanges() accept an array of objects" whenever I use markRanges() in an iframe.

### ISSUE THREAD

**Issue by ankified** [angezid/advanced-mark.js#17]
Hi @angezid. I've been experimenting with advanced-mark.js for a few days but now I'm stuck in the problem I'll describe below. Maybe I'm doing something wrong, so I ask for directions on how to get the code to work as expected.

# How to reproduce:

1. Get the source-code from https://raw.githubusercontent.com/angezid/advanced-mark.js/master/dist/mark.js
2. Access some page that has at least one iframe (I'm testing on: https://www.w3schools.com/html/html_iframe.asp)
3. Open the console tab in Dev Tools
4. Paste the source-code in the console, then hit enter
5. Paste the script below in the console, then hit enter:
```
var iframes = document.getElementsByTagName('iframe');
const instance = new Mark(iframes);
let start = 0;
let length = 10
let ranges = [{start: start, length: length}];
instance.markRanges(ranges, {
  iframes : true,
    debug: true,
});
```
6. Check the console for the error message below:
![image](https://github.com/angezid/advanced-mark.js/assets/75060185/8eea6fe1-2c31-442c-a611-dc93c5aa877f)

# What I've tried:
1. Check if I can use `mark()` instead of  `markRanges()` successfully. 
*Result*: I can.
2. Write console.log messages in the `markRanges` function to check what's the line the code stops working
*Result*: It stops right before `this.wrapRanges(ranges, function (node, range, match, index) {`

# Info:
- I'm using Brave browser version 1.64.109 Chromium: 123.0.6312.58 64 bits and Windows 11.

**Comment by angezid** [comment]
@ankified thanks for reporting. It's really bug - the problem causes `ranges.some(obj => obj.start && obj.length)` in  
 `if (Array.isArray(ranges) && ranges.some(obj => obj.start && obj.length)) {}` then the array have a single item.  

The fix is `ranges.some(obj => typeof obj.start !== 'undefined' && typeof obj.length !== 'undefined')`.

Also, use `querySelectorAll('iframe')` or `querySelector('iframe')` instead of `getElementsByTagName()`  when dealing with iframes because of:  

> The Element.getElementsByTagName() method returns a live HTMLCollection of elements with the given tag name. All descendants of the specified element are searched, but not the element itself.
