### ISSUE TITLE
Merging with main library

### ISSUE THREAD

**Issue by Nickersoft** [angezid/advanced-mark.js#6]
Hey @angezid!

I recently adopted using mark.js (more specifically, _this_ fork of the library), and love the changes you've introduced, especially around performance. I saw you have a [standing invitation](https://github.com/julmot/mark.js/issues/481#issuecomment-1203803899) from Julian to become an official maintainer on the original repo.

Would love to see these changes get merged into the upstream, so that way it can be versioned normally (right now I just have this GitHub repo's "master" branch added to my package.json). Just my two cents :)

Keep up the good work!! 🎉

**Comment by angezid** [comment]
>  I saw you have a standing invitation from Julian to become an official maintainer on the original repo.

I'm afraid to become a maintainer on the original repo. There are some reasons for this.

> Would love to see these changes get merged into the upstream,

This upstream streams nothing more than four years. The merge solves nothing.
There is a need to release npm package. This what I am currently going to do.

The problem is, I didn't foresee that simple PR was going so far. In order to release the package, I need to rename this fork (break cloning) or create a new repo.
For further development new repo more preferable - the existing code requires a lot of refactoring, optimization, and rewriting not only for performance or readability reasons, but also to reduce the size of the library. This inevitably will create problems, e.g. with backward compatibility ...

**Comment by Nickersoft** [comment]
Hey @angezid, thanks for the reply – I think that makes sense. Maintaining an open-source repo, especially someone else's, is hard work! I'm definitely in favor of renaming, or at the very least, getting an official package released that can be versioned. I think the work you're doing is great and super important, as I've been scouring the web and shockingly wasn't able to find any modern, actively maintained projects that solve the problem that mark.js tackles. Most "highlighting" libraries refer to code highlighting lol. 

So I'll definitely keep my eye on this repo and look forward to seeing what you decide to do with it! Keep it up 💪🏻

**Comment by angezid** [comment]
> I've been scouring the web and shockingly wasn't able to find any modern, actively maintained projects that solve the problem that mark.js tackles.  Most "highlighting" libraries refer to code highlighting lol.

Yes, there is no anything decent around. Syntax highlighting is much more widely used.
Weekly Downloads: highlight.js - 4,024,592, prism.js - 3,745,931, mark.js - 193,871

NPM package is released. Happy highlighting!

**Comment by Nickersoft** [comment]
You rock @angezid! One small caveat – it may be helpful to either bundle TypeScript types for this package, or add them to DefinitelyTyped. Currently getting around this using an alias:

```json
"@types/mark.js": "^8.11.8",
"mark.js": "npm:advanced-mark.js@^1.0.2",
```

**Comment by angezid** [comment]
@Nickersoft thanks for hint.

I added types declaration files to the repo `dist` folder. They 'satisfied' the compiler v4.7.0 with option `"esModuleInterop": true` and have to be tested before adding them to npm package.

A single declaration file on DefinitelyTyped creates dependency on `jquery` for 'vanilla' javascript modules.
With individual declaration files in `dist` folder - there is no such dependency.
Also, it is possible for `es6` modules, to avoid the requirement of compiler option `"esModuleInterop": true`, using `export default Mark;` instead of `export = Mark;`.
